laravel/app/routes.php
<?php

Route::get('teste', function(){
	echo "abc";
});

Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));

Route::get('home', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::post('home', array('as' => 'home.ajax', 'uses' => 'AjaxController@home'));

Route::get('empresa', array('as' => 'empresa', 'uses' => 'EmpresaController@index'));
Route::post('empresa', array('as' => 'empresa.ajax', 'uses' => 'AjaxController@empresa'));

Route::get('produtos', array('as' => 'produtos', 'uses' => 'ProdutosController@index'));
Route::post('produtos', array('as' => 'produtos.ajax', 'uses' => 'AjaxController@produtos'));
Route::get('produtos/categorias/{slug?}', array('as' => 'produtos.categorias', 'uses' => 'ProdutosController@categoria'));
Route::post('produtos/categorias/{slug?}', array('as' => 'produtos.categorias.ajax', 'uses' => 'AjaxController@categoria'));
Route::get('produtos/detalhes/{slug?}', array('as' => 'produtos.detalhes', 'uses' => 'ProdutosController@detalhes'));
Route::post('produtos/detalhes/{slug?}', array('as' => 'produtos.detalhes.ajax', 'uses' => 'AjaxController@detalhes'));

Route::get('lancamentos', array('as' => 'lancamentos', 'uses' => 'LancamentosController@index'));
Route::post('lancamentos', array('as' => 'lancamentos.ajax', 'uses' => 'AjaxController@lancamentos'));
Route::get('lancamento/{slug?}', array('as' => 'lancamentos.detalhes', 'uses' => 'LancamentosController@detalhes'));
Route::post('lancamento/{slug?}', array('as' => 'lancamentos.detalhes.ajax', 'uses' => 'AjaxController@lancamentosDetalhes'));

Route::get('novidades', array('as' => 'novidades', 'uses' => 'NovidadesController@index'));
Route::post('novidades', array('as' => 'novidades.ajax', 'uses' => 'AjaxController@novidades'));

Route::get('clippings', array('as' => 'clippings', 'uses' => 'ClippingsController@index'));
Route::post('clippings', array('as' => 'clippings.ajax', 'uses' => 'AjaxController@clippings'));

Route::get('contato', array('as' => 'contato', 'uses' => 'ContatoController@index'));
Route::post('contato', array('as' => 'contato.ajax', 'uses' => 'AjaxController@contato'));
Route::post('contato/enviar', array('as' => 'contato.enviar', 'uses' => 'ContatoController@enviar'));
Route::post('contato/newsletter', array('as' => 'contato.newsletter', 'uses' => 'ContatoController@newsletter'));

Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
    Route::resource('usuarios', 'Painel\UsuariosController');
    Route::resource('banners', 'Painel\BannersController');
	Route::resource('chamadas', 'Painel\ChamadasController');
	Route::resource('cadastros', 'Painel\CadastrosController');
	Route::get('painel/cadastros/download', array('as' => 'painel.cadastros.download', 'uses' => 'Painel\CadastrosController@download'));
	Route::resource('destaques', 'Painel\DestaquesController');
	Route::resource('empresa', 'Painel\EmpresaController');
	Route::resource('produtoscategorias', 'Painel\ProdutosCategoriasController');
	Route::resource('produtos', 'Painel\ProdutosController');
	Route::resource('produtosimagens', 'Painel\ProdutosImagensController');
	Route::resource('lancamentos', 'Painel\LancamentosController');
	Route::resource('novidades', 'Painel\NovidadesController');
	Route::resource('clippings', 'Painel\ClippingsController');
	Route::resource('clippingimagens', 'Painel\ClippingImagensController');
	Route::resource('contato', 'Painel\ContatoController');
//NOVASROTASDOPAINEL//
});

laravel/app/controllers/painel/ProdutosImagensController.php
<?php

namespace Painel;

use \View, \Input, \Str, \Session, \Redirect, \Hash, \Thumb, \File, \Produto, \ProdutosImagem;

class ProdutosImagensController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	protected $limiteInsercao = false;

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$produtos_id = Input::get('produtos_id');

		if(!$produtos_id)
			return Redirect::back();

		$this->layout->content = View::make('backend.produtosimagens.index')->with('registros', ProdutosImagem::orderBy('ordem', 'ASC')->where('produtos_id', $produtos_id)->get())
																			->with('produto', Produto::find($produtos_id));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$produtos_id = Input::get('produtos_id');

		if(!$produtos_id)
			return Redirect::back();

		$this->layout->content = View::make('backend.produtosimagens.form')->with('produto', Produto::find($produtos_id));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new ProdutosImagem;

		$object->produtos_id = Input::get('produtos_id');

		$t=date('YmdHis');
		$imagem = Thumb::make('imagem', 55, 55, 'produtosimagens/thumbs/', $t);
		Thumb::make('imagem', 940, null, 'produtosimagens/', $t);
		if($imagem) $object->imagem = $imagem;

		try {

			$object->save();

			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Imagem criado com sucesso.');
			return Redirect::route('painel.produtosimagens.index', array('produtos_id' => $object->produtos_id));

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Imagem!'));	

		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$imagem = ProdutosImagem::find($id);

		$produto = Produto::find($imagem->produtos_id);

		$this->layout->content = View::make('backend.produtosimagens.edit')->with('registro', $imagem)
																		   ->with('produto', $produto);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = ProdutosImagem::find($id);

		$object->produtos_id = Input::get('produtos_id');

		$t=date('YmdHis');
		$imagem = Thumb::make('imagem', 55, 55, 'produtosimagens/thumbs/', $t);
		Thumb::make('imagem', 940, null, 'produtosimagens/', $t);
		if($imagem) $object->imagem = $imagem;

		try {

			$object->save();
			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Imagem alterado com sucesso.');
			return Redirect::route('painel.produtosimagens.index', array('produtos_id' => $object->produtos_id));

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Imagem!'));

		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = ProdutosImagem::find($id);
		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Imagem removido com sucesso.');

		return Redirect::route('painel.produtosimagens.index');
	}

}

laravel/app/views/backend/produtosimagens/edit.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Editar Imagem do Produto: {{Produto::find($produto->id)->titulo}}
        </h2>  

		{{ Form::open( array('route' => array('painel.produtosimagens.update', $registro->id), 'files' => true, 'method' => 'put') ) }}
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif

				<div class="form-group">
					@if($registro->imagem)
						Imagem Atual<br>
						<img src="assets/images/produtosimagens/{{$registro->imagem}}"><br>
					@endif
					<label for="inputImagem">Trocar Imagem</label>
					<input type="file" class="form-control" id="inputImagem" name="imagem">
				</div>

				<input type="hidden" name="produtos_id" value="{{$produto->id}}">

				<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

				<a href="{{URL::route('painel.produtosimagens.index', array('produtos_id' => $produto->id))}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/produtosimagens/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Adicionar Imagem do Produto: {{Produto::find($produto->id)->titulo}}
        </h2>  

		<form action="{{URL::route('painel.produtosimagens.store')}}" method="post" enctype="multipart/form-data">
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif

				<div class="form-group">
					<label for="inputImagem">Imagem</label>
					<input type="file" class="form-control" id="inputImagem" name="imagem" required>
				</div>
				
				<input type="hidden" name="produtos_id" value="{{$produto->id}}">

				<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

				<a href="{{URL::route('painel.produtosimagens.index', array('produtos_id' => $produto->id))}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/produtosimagens/index.blade.php
@section('conteudo')

<div class="container">

    @if(Session::has('sucesso'))
        <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

    @if($errors->any())
        <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
    @endif

    <h2>
        Imagens do Produto: {{Produto::find($produto->id)->titulo}} <a href='{{ URL::route('painel.produtosimagens.create', array('produtos_id' => $produto->id)) }}' class='btn btn-success btn-sm pull-right'><span class='glyphicon glyphicon-plus-sign'></span> Adicionar Imagem</a>
    </h2>

    <a href="{{URL::route('painel.produtos.index')}}" class="btn btn-default btn-sm" title="Voltar para Produtos">Voltar para Produtos</a>

    <table class='table table-striped table-bordered table-hover table-sortable' data-tabela='produtos_imagens'>

        <thead>
            <tr>
                <th>Ordenar</th>
				<th>Imagem</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)

            <tr class="tr-row" id="row_{{ $registro->id }}">
                <td class='move-actions'><a href='#' class='btn btn-info btn-move btn-small'>mover</a></td>
				<td><img src='assets/images/produtosimagens/thumbs/{{ $registro->imagem }}' style='max-width:150px'></td>
                <td class="crud-actions">
                    <a href='{{ URL::route('painel.produtosimagens.edit', $registro->id ) }}' class='btn btn-primary btn-sm'>editar</a>
					{{ Form::open(array('route' => array('painel.produtosimagens.destroy', $registro->id), 'method' => 'delete')) }}
						<button type='submit' class='btn btn-danger btn-sm btn-delete'>excluir</button>
					{{ Form::close() }}                    
                </td>
            </tr>

        @endforeach
        </tbody>

    </table>

    
</div>

@stop