laravel/app/routes.php
<?php

Route::get('teste', function(){
	echo "abc";
});

Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));

Route::get('home', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::post('home', array('as' => 'home.ajax', 'uses' => 'AjaxController@home'));

Route::get('empresa', array('as' => 'empresa', 'uses' => 'EmpresaController@index'));
Route::post('empresa', array('as' => 'empresa.ajax', 'uses' => 'AjaxController@empresa'));

Route::get('produtos', array('as' => 'produtos', 'uses' => 'ProdutosController@index'));
Route::post('produtos', array('as' => 'produtos.ajax', 'uses' => 'AjaxController@produtos'));
Route::get('produtos/categorias/{slug?}', array('as' => 'produtos.categorias', 'uses' => 'ProdutosController@categoria'));
Route::post('produtos/categorias/{slug?}', array('as' => 'produtos.categorias.ajax', 'uses' => 'AjaxController@categoria'));
Route::get('produtos/detalhes/{slug?}', array('as' => 'produtos.detalhes', 'uses' => 'ProdutosController@detalhes'));
Route::post('produtos/detalhes/{slug?}', array('as' => 'produtos.detalhes.ajax', 'uses' => 'AjaxController@detalhes'));

Route::get('lancamentos', array('as' => 'lancamentos', 'uses' => 'LancamentosController@index'));
Route::post('lancamentos', array('as' => 'lancamentos.ajax', 'uses' => 'AjaxController@lancamentos'));
Route::get('lancamento/{slug?}', array('as' => 'lancamentos.detalhes', 'uses' => 'LancamentosController@detalhes'));
Route::post('lancamento/{slug?}', array('as' => 'lancamentos.detalhes.ajax', 'uses' => 'AjaxController@lancamentosDetalhes'));

Route::get('novidades', array('as' => 'novidades', 'uses' => 'NovidadesController@index'));
Route::post('novidades', array('as' => 'novidades.ajax', 'uses' => 'AjaxController@novidades'));

Route::get('clippings', array('as' => 'clippings', 'uses' => 'ClippingsController@index'));
Route::post('clippings', array('as' => 'clippings.ajax', 'uses' => 'AjaxController@clippings'));

Route::get('contato', array('as' => 'contato', 'uses' => 'ContatoController@index'));
Route::post('contato', array('as' => 'contato.ajax', 'uses' => 'AjaxController@contato'));
Route::post('contato/enviar', array('as' => 'contato.enviar', 'uses' => 'ContatoController@enviar'));
Route::post('contato/newsletter', array('as' => 'contato.newsletter', 'uses' => 'ContatoController@newsletter'));

Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
    Route::resource('usuarios', 'Painel\UsuariosController');
    Route::resource('banners', 'Painel\BannersController');
	Route::resource('chamadas', 'Painel\ChamadasController');
	Route::resource('cadastros', 'Painel\CadastrosController');
	Route::get('painel/cadastros/download', array('as' => 'painel.cadastros.download', 'uses' => 'Painel\CadastrosController@download'));
	Route::resource('destaques', 'Painel\DestaquesController');
	Route::resource('empresa', 'Painel\EmpresaController');
	Route::resource('produtoscategorias', 'Painel\ProdutosCategoriasController');
	Route::resource('produtos', 'Painel\ProdutosController');
	Route::resource('produtosimagens', 'Painel\ProdutosImagensController');
	Route::resource('lancamentos', 'Painel\LancamentosController');
	Route::resource('novidades', 'Painel\NovidadesController');
	Route::resource('clippings', 'Painel\ClippingsController');
	Route::resource('clippingimagens', 'Painel\ClippingImagensController');
	Route::resource('contato', 'Painel\ContatoController');
//NOVASROTASDOPAINEL//
});

laravel/app/models/Destaque.php
<?php

class Destaque extends Eloquent
{

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'destaques';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array();

	// array of attributes we CAN set on the backend
    protected $fillable = array('', 'created_at', 'updated_at');

    // and those we CAN'T set on the backend
    protected $guarded = array('id');

}

laravel/app/controllers/painel/DestaquesController.php
<?php

namespace Painel;

use \View, \Input, \Str, \DB, \Session, \Redirect, \Hash, \Thumb, \File, \Destaque, \Produto;

class DestaquesController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	public $limiteInsercao = '4';

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout->content = View::make('backend.destaques.index')->with('registros', Destaque::orderBy('ordem', 'ASC')->get())->with('limiteInsercao', $this->limiteInsercao);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		if(count(Destaque::all()) > 0)
			$produtos = DB::table('produtos')->whereNotIn('id', DB::table('destaques')->lists('produtos_id'))->get();
		else
			$produtos = Produto::orderBy('titulo')->get();

		$this->layout->content = View::make('backend.destaques.form')->with('produtos', $produtos);
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new Destaque;

		$object->produtos_id = Input::get('produtos_id');

		if($this->limiteInsercao && sizeof(Destaque::all()) >= $this->limiteInsercao)
			return Redirect::back()->withErrors(array('Número máximo de Registros atingido!'));

		try {

			$object->save();

			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Destaque criado com sucesso.');
			return Redirect::route('painel.destaques.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Destaque!'));	

		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		if(count(Destaque::all()) > 0)
			$produtos = DB::table('produtos')->whereNotIn('id', DB::table('destaques')->lists('produtos_id'))->get();
		else
			$produtos = Produto::orderBy('titulo')->get();
					
		$this->layout->content = View::make('backend.destaques.edit')->with('registro', Destaque::find($id))->with('produtos', $produtos);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = Destaque::find($id);

		$object->produtos_id = Input::get('produtos_id');

	
		try {

			$object->save();
			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Destaque alterado com sucesso.');
			return Redirect::route('painel.destaques.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Destaque!'));

		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = Destaque::find($id);
		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Destaque removido com sucesso.');

		return Redirect::route('painel.destaques.index');
	}

}

laravel/app/views/backend/destaques/edit.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Editar Destaque
        </h2>  

		{{ Form::open( array('route' => array('painel.destaques.update', $registro->id), 'files' => true, 'method' => 'put') ) }}
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	


				<div class="form-group">
					<label for="inputProduto em Destaque">Produto em Destaque</label>					 
					<select	name="produtos_id" class="form-control" id="inputProduto em Destaque" required>
						<option value="">Selecione</option>
						@if($produtos)
							@foreach($produtos as $produto)
								<option value="{{$produto->id}}" @if($produto->id == $registro->produtos_id) selected @endif>{{$produto->titulo}}</option>
							@endforeach
						@endif
					</select>
				</div>
				

				<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

				<a href="{{URL::route('painel.destaques.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/destaques/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Adicionar Destaque
        </h2>  

		<form action="{{URL::route('painel.destaques.store')}}" method="post" enctype="multipart/form-data">
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif


				<div class="form-group">
					<label for="inputProduto">Produto em Destaque</label>					 
					<select	name="produtos_id" class="form-control" id="inputProduto" required>
						<option value="">Selecione</option>
						@if($produtos)
							@foreach($produtos as $produto)
								<option value="{{$produto->id}}">{{$produto->titulo}}</option>
							@endforeach
						@endif
					</select>
				</div>
				

				<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

				<a href="{{URL::route('painel.destaques.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/destaques/index.blade.php
@section('conteudo')

<div class="container">

    @if(Session::has('sucesso'))
        <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

    @if($errors->any())
        <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
    @endif

    <h2>
        Destaques @if(sizeof(Destaque::all()) < $limiteInsercao) <a href='{{ URL::route('painel.destaques.create') }}' class='btn btn-success btn-sm pull-right'><span class='glyphicon glyphicon-plus-sign'></span> Adicionar Destaque</a> @endif
    </h2>

    <table class='table table-striped table-bordered table-hover table-sortable' data-tabela='destaques'>

        <thead>
            <tr>
                <th>Ordenar</th>
				<th>Produto em Destaque</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)

            <tr class="tr-row" id="row_{{ $registro->id }}">
                <td class='move-actions'><a href='#' class='btn btn-info btn-move btn-sm'>mover</a></td>
				<td>{{ Produto::find($registro->produtos_id)->prefixo .' '. Produto::find($registro->produtos_id)->titulo }}</td>
                <td class="crud-actions">
                    <a href='{{ URL::route('painel.destaques.edit', $registro->id ) }}' class='btn btn-primary btn-sm'>editar</a>
					{{ Form::open(array('route' => array('painel.destaques.destroy', $registro->id), 'method' => 'delete')) }}
						<button type='submit' class='btn btn-danger btn-sm btn-delete'>excluir</button>
					{{ Form::close() }}                    
                </td>
            </tr>

        @endforeach
        </tbody>

    </table>

    
</div>

@stop