laravel/app/routes.php
<?php

Route::get('teste', function(){
	echo "abc";
});

Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));

Route::get('home', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::post('home', array('as' => 'home.ajax', 'uses' => 'AjaxController@home'));

Route::get('empresa', array('as' => 'empresa', 'uses' => 'EmpresaController@index'));
Route::post('empresa', array('as' => 'empresa.ajax', 'uses' => 'AjaxController@empresa'));

Route::get('produtos', array('as' => 'produtos', 'uses' => 'ProdutosController@index'));
Route::post('produtos', array('as' => 'produtos.ajax', 'uses' => 'AjaxController@produtos'));
Route::get('produtos/categorias/{slug?}', array('as' => 'produtos.categorias', 'uses' => 'ProdutosController@categoria'));
Route::post('produtos/categorias/{slug?}', array('as' => 'produtos.categorias.ajax', 'uses' => 'AjaxController@categoria'));
Route::get('produtos/detalhes/{slug?}', array('as' => 'produtos.detalhes', 'uses' => 'ProdutosController@detalhes'));
Route::post('produtos/detalhes/{slug?}', array('as' => 'produtos.detalhes.ajax', 'uses' => 'AjaxController@detalhes'));

Route::get('lancamentos', array('as' => 'lancamentos', 'uses' => 'LancamentosController@index'));
Route::post('lancamentos', array('as' => 'lancamentos.ajax', 'uses' => 'AjaxController@lancamentos'));
Route::get('lancamento/{slug?}', array('as' => 'lancamentos.detalhes', 'uses' => 'LancamentosController@detalhes'));
Route::post('lancamento/{slug?}', array('as' => 'lancamentos.detalhes.ajax', 'uses' => 'AjaxController@lancamentosDetalhes'));

Route::get('novidades', array('as' => 'novidades', 'uses' => 'NovidadesController@index'));
Route::post('novidades', array('as' => 'novidades.ajax', 'uses' => 'AjaxController@novidades'));

Route::get('clippings', array('as' => 'clippings', 'uses' => 'ClippingsController@index'));
Route::post('clippings', array('as' => 'clippings.ajax', 'uses' => 'AjaxController@clippings'));

Route::get('contato', array('as' => 'contato', 'uses' => 'ContatoController@index'));
Route::post('contato', array('as' => 'contato.ajax', 'uses' => 'AjaxController@contato'));
Route::post('contato/enviar', array('as' => 'contato.enviar', 'uses' => 'ContatoController@enviar'));
Route::post('contato/newsletter', array('as' => 'contato.newsletter', 'uses' => 'ContatoController@newsletter'));

Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
    Route::resource('usuarios', 'Painel\UsuariosController');
    Route::resource('banners', 'Painel\BannersController');
	Route::resource('chamadas', 'Painel\ChamadasController');
	Route::resource('cadastros', 'Painel\CadastrosController');
	Route::get('painel/cadastros/download', array('as' => 'painel.cadastros.download', 'uses' => 'Painel\CadastrosController@download'));
	Route::resource('destaques', 'Painel\DestaquesController');
	Route::resource('empresa', 'Painel\EmpresaController');
	Route::resource('produtoscategorias', 'Painel\ProdutosCategoriasController');
	Route::resource('produtos', 'Painel\ProdutosController');
	Route::resource('produtosimagens', 'Painel\ProdutosImagensController');
	Route::resource('lancamentos', 'Painel\LancamentosController');
	Route::resource('novidades', 'Painel\NovidadesController');
	Route::resource('clippings', 'Painel\ClippingsController');
	Route::resource('clippingimagens', 'Painel\ClippingImagensController');
	Route::resource('contato', 'Painel\ContatoController');
//NOVASROTASDOPAINEL//
});

laravel/app/models/Produto.php
<?php

class Produto extends Eloquent
{

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'produtos';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array();

	// array of attributes we CAN set on the backend
    protected $fillable = array('', 'created_at', 'updated_at');

    // and those we CAN'T set on the backend
    protected $guarded = array('id');

    protected function categoria()
    {
    	return $this->belongsTo('Categoria', 'produtos_categorias_id');
    }

    protected function imagens()
    {
    	return $this->hasMany('ProdutosImagem', 'produtos_id');
    }
}

laravel/app/controllers/ProdutosController.php
<?php

use \Produto;

class ProdutosController extends BaseController {

	protected $layout = 'frontend.templates.index';

	public function index()
	{
		$this->layout->content = View::make('frontend.produtos.index')->with('categorias', Categoria::orderBy('ordem', 'asc')->get())
																	  ->with('produtos', Produto::orderBy('ordem', 'asc')->paginate(9));
	}

	public function categoria($slug_categoria = ''){
		$categoria = Categoria::where('slug', '=', $slug_categoria)->first();

		if(is_null($categoria)){
			App::abort('404');
		}

		$produtos = $categoria->produtos()->paginate(9);

		$this->layout->content = View::make('frontend.produtos.index')->with('detalheCategoria', $categoria)
																	  ->with('categorias', Categoria::orderBy('ordem', 'asc')->get())
																	  ->with('produtos', $produtos);
	}

	public function detalhes($slug_produto = ''){
		$produto = Produto::where('slug', '=', $slug_produto)->first();

		if(is_null($produto)){
			App::abort('404');
		}

		$categoria = $produto->categoria;

		$this->layout->content = View::make('frontend.produtos.detalhes')->with('detalheCategoria', $categoria)
																	  	 ->with('categorias', Categoria::orderBy('ordem', 'asc')->get())
																	  	 ->with('produto', $produto);
	}

}

laravel/app/controllers/painel/ProdutosController.php
<?php

namespace Painel;

use \View, \Input, \Str, \Session, \Redirect, \Hash, \Thumb, \File, \Produto, \Categoria, \Destaque, \Lancamento;

class ProdutosController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	protected $limiteInsercao = false;

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$categorias_id = Input::get('categorias_id');
		$categoria = Categoria::find($categorias_id);

		if(is_null($categoria)){
			$produtos = Produto::orderBy('ordem', 'ASC')->get();
		}else{
			$produtos = $categoria->produtos;
		}

		$this->layout->content = View::make('backend.produtos.index')->with('registros', $produtos)
																	 ->with('categorias', Categoria::orderBy('ordem', 'ASC')->get())
																	 ->with('categoria', $categoria);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('backend.produtos.form')->with('categorias', Categoria::orderBy('titulo', 'asc')->get());
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new Produto;

		$object->prefixo = Input::get('prefixo');
		$object->titulo = Input::get('titulo');
		$object->produtos_categorias_id = Input::get('produtos_categorias_id');

		$t=date('YmdHis');
		$imagem = Thumb::make('imagem', 200, 200, 'produtos/thumbs/', $t, '#FFFFFF', false);
		Thumb::make('imagem', 450, 450, 'produtos/', $t, '#FFFFFF', false);
		if($imagem) $object->imagem = $imagem;

		try {

			$object->save();
			$object->slug = Str::slug($object->id.'-'.$object->prefixo.'-'.$object->titulo);
			$object->save();

			if(Input::has('lancamento') && Input::get('lancamento') == 1){
				$lancamento = new Lancamento;
				$lancamento->produtos_id = $object->id;
				$lancamento->save();
			}

			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Produto criado com sucesso.');
			return Redirect::route('painel.produtos.index', array('categorias_id' => $object->produtos_categorias_id));

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Produto!'));	

		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('backend.produtos.edit')->with('registro', Produto::find($id))
																	->with('categorias', Categoria::orderBy('titulo', 'asc')->get());
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = Produto::find($id);

		$object->prefixo = Input::get('prefixo');
		$object->titulo = Input::get('titulo');
		$object->produtos_categorias_id = Input::get('produtos_categorias_id');
		
		$t=date('YmdHis');
		$imagem = Thumb::make('imagem', 200, 200, 'produtos/thumbs/', $t, '#FFFFFF', false);
		Thumb::make('imagem', 450, 450, 'produtos/', $t, '#FFFFFF', false);
		if($imagem) $object->imagem = $imagem;

		try {

			$object->save();
			$object->slug = Str::slug($object->id.'-'.$object->prefixo.'-'.$object->titulo);
			$object->save();
			
			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Produto alterado com sucesso.');
			return Redirect::route('painel.produtos.index', array('categorias_id' => $object->produtos_categorias_id));

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Produto!'));

		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		Destaque::where('produtos_id', '=', $id)->delete();
		Lancamento::where('produtos_id', '=', $id)->delete();
		\ProdutosImagem::where('produtos_id', '=', $id)->delete();

		$object = Produto::find($id);

		$cat_id = $object->produtos_categorias_id;

		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Produto removido com sucesso.');

		return Redirect::route('painel.produtos.index', array('categorias_id' => $cat_id));
	}

}

laravel/app/views/backend/produtos/edit.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Editar Produto
        </h2>  

		{{ Form::open( array('route' => array('painel.produtos.update', $registro->id), 'files' => true, 'method' => 'put') ) }}
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	

				<div class="form-group">
					<label for="inputCategoria">Categoria do Produto</label>					 
					<select	name="produtos_categorias_id" class="form-control" id="inputCategoria" required>
						<option value="">Selecione</option>
						@if($categorias)
							@foreach($categorias as $categoria)
								<option value="{{$categoria->id}}" @if($categoria->id == $registro->produtos_categorias_id) selected @endif>{{$categoria->titulo}}</option>
							@endforeach
						@endif
					</select>
				</div>

				<div class="form-group">
					<label for="inputPrefixo">Prefixo</label>
					<input type="text" class="form-control" id="inputPrefixo" name="prefixo" value="{{$registro->prefixo}}" >
				</div>
				<div class="form-group">
					<label for="inputTítulo">Título</label>
					<input type="text" class="form-control" id="inputTítulo" name="titulo" value="{{$registro->titulo}}" required>
				</div>
				<div class="form-group">
					@if($registro->imagem)
						Imagem Atual<br>
						<img src="assets/images/produtos/{{$registro->imagem}}"><br>
					@endif
					<label for="inputImagem">Trocar Imagem</label>
					<input type="file" class="form-control" id="inputImagem" name="imagem">
				</div>
				

				<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

				<a href="{{URL::route('painel.produtos.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/produtos/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Adicionar Produto
        </h2>  

		<form action="{{URL::route('painel.produtos.store')}}" method="post" enctype="multipart/form-data">
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif

				<div class="form-group">
					<label for="inputCategoria">Categoria do Produto</label>					 
					<select	name="produtos_categorias_id" class="form-control" id="inputCategoria" required>
						<option value="">Selecione</option>
						@if($categorias)
							@foreach($categorias as $categoria)
								<option value="{{$categoria->id}}">{{$categoria->titulo}}</option>
							@endforeach
						@endif
					</select>
				</div>

				<div class="form-group">
					<label for="inputPrefixo">Prefixo</label>
					<input type="text" class="form-control" id="inputPrefixo" name="prefixo" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['prefixo'] }}" @endif >
				</div>

				<div class="form-group">
					<label for="inputTítulo">Título</label>
					<input type="text" class="form-control" id="inputTítulo" name="titulo" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['titulo'] }}" @endif required>
				</div>

				<div class="form-group">
					<label for="inputImagem">Imagem</label>
					<input type="file" class="form-control" id="inputImagem" name="imagem" required>
				</div>
				
				<div class="form-group">
					<label><input type="checkbox" value="1" name="lancamento"> Cadastrar Produto como lançamento</label>					
				</div>

				<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

				<a href="{{URL::route('painel.produtos.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/produtos/index.blade.php
@section('conteudo')

<div class="container">

    @if(Session::has('sucesso'))
        <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

    @if($errors->any())
        <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
    @endif

    <h2>
        Produtos @if(!is_null($categoria) && isset($categoria->titulo)) - {{$categoria->titulo}} @endif <a href='{{ URL::route('painel.produtos.create') }}' class='btn btn-success btn-sm pull-right'><span class='glyphicon glyphicon-plus-sign'></span> Adicionar Produto</a>
    </h2>

    <hr>
    @if($categorias)
        Filtrar por Categoria: 
        <div class="btn-group">
        @foreach($categorias as $cat)
            @if(!is_null($categoria) && isset($categoria->id) && $categoria->id == $cat->id)
                <a href="{{URL::route('painel.produtos.index', array('categorias_id' => $cat->id))}}" class="btn btn-sm btn-info">{{$cat->titulo}}</a>
            @else
                <a href="{{URL::route('painel.produtos.index', array('categorias_id' => $cat->id))}}" class="btn btn-sm btn-default">{{$cat->titulo}}</a>
            @endif
        @endforeach
        </div>
    @endif

    <table class='table table-striped table-bordered table-hover table-sortable' data-tabela='produtos'>

        <thead>
            <tr>
                @if(!is_null($categoria))
                    <th>Ordenar</th>
                @endif
				<th>Título</th>
                <th>Imagens</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)

            <tr class="tr-row" id="row_{{ $registro->id }}">
                @if(!is_null($categoria))
                    <td class='move-actions'><a href='#' class='btn btn-info btn-move btn-sm'>mover</a></td>
                @endif
				<td>{{ $registro->prefixo.' - '.$registro->titulo }}</td>
                <td><a href="{{URL::route('painel.produtosimagens.index', array('produtos_id' => $registro->id))}}" title="Gerenciar Imagens do Produto" class="btn btn-default btn-sm">gerenciar</a></td>
				<td class="crud-actions">
                    <a href='{{ URL::route('painel.produtos.edit', $registro->id ) }}' class='btn btn-primary btn-sm'>editar</a>
					{{ Form::open(array('route' => array('painel.produtos.destroy', $registro->id), 'method' => 'delete')) }}
						<button type='submit' class='btn btn-danger btn-sm btn-delete'>excluir</button>
					{{ Form::close() }}
                </td>
            </tr>

        @endforeach
        </tbody>

    </table>

    
</div>

@stop